CREATE DATABASE IF NOT EXISTS testdb;
USE testdb;

CREATE TABLE IF NOT EXISTS `person` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `nama` VARCHAR(200) NOT NULL,
    `alamat` VARCHAR(200) NOT NULL
);

INSERT INTO `person` (`nama`, `alamat`) VALUES
('coba', 'cobafdsfd'),
('ana 5', 'arab'),
('Tari', 'Dakota'),
('Cak Gembul x', 'Surabaya gg gg hhhhhh'),
('Mc Greg x', 'Ujung Berung y'),
('SENTOT xx', 'Bandung yhhh'),
('Ni Made vv ff', 'Ujung Berung'),
('Nama1 xx g', 'Alamat1 yy fg'),
('Nama12', 'Alamat14'),
('ANNAA', 'Jakarta'),
('ANNA', 'Jakartaaa'),
('xx', 'zzz'),
('dika1', 'Bandung'),
('nama', 'Bandung 123'),
('', 'Bandung'),
('ANNA 1', 'Jakarta 1'),
('ANNA 3', 'Jakarta 3'),
('SENTOT 1234', 'Bandung 123'),
('ANNAA', 'Jakarta'),
('Mc Greg 123', 'USA 123'),
('SENTOT', 'Bandung'),
('Ni Made 1', 'Bali 1'),
('Ni Made', 'Bali'),
('Cak Gembul', 'Surabaya'),
('Cak Gembul', 'Surabaya'),
('SENTOT', 'Bandung'),
('Cak Gembul', 'Surabaya 5'),
('ANNAA', 'Jakarta xx'),
('mk', 'mk'),
('judi', 'bandung'),
('judi x', 'bandung'),
('maman', 'cimahi'),
('ana 5g', 'arab xx vg'),
('Cak Gembul x', 'Surabaya b'),
('Muhammad Kemal Ilyasa Margana ', '1'),
('azx', 'xx'),
('test 2', 'terdddddddasdasd'),
('', ''),
('Tari', 'Dakota'),
('Mc Greg', 'USA'),
('Ni Made vv', 'Bali'),
('Ni Made vv', 'Bali'),
('Ni Made vv', 'Bali'),
('Ni Made vv', 'Bali'),
('Ni Made vv', 'Bali'),
('Mc Greg', 'USA'),
('Cak Gembul', 'Surabaya'),
('ana 5', 'arab xx v'),
('Tari', 'Dakota'),
('ana 5', 'arab xx v'),
('ana 5', 'arab xx v'),
('ana 5', 'arab xx v'),
('nama yx', 'alamat yx'),
('Cak Gembul', 'Surabaya'),
('nama yx', 'alamat yx'),
('ana 5', 'arab xx v'),
('', ''),
('',''),
('ana 5', 'arab xx v'),
('ana 5', 'arab xx v'),
('ana 5', 'arab xx v'),
('Nama1 xx g', 'Alamat1 yy fg'),
('ana 5', 'arab xx v'),
('ana 5', 'arab xx v'),
('Mc Greg', 'USA'),
('nama yx', 'alamat yx'),
('Mc Greg', 'USA'),
('ANNAA', 'Jakarta'),
('ana 5', 'arab xx v'),
('YAMAN NUR M', 'BALI'),
('Fulan', 'Fulan'),
('', ''),
('', ''),
('Yaman', 'Mnur'),
('', ''),
('', ''),
('ERWIN', 'BANDUNG'),
('ERWIN', 'BANDUNG'),
('SOLEH', 'JAWA'),
('Siapakah', 'Dimanakah'),
('Cak Gembul x ydg', 'Surabaya gg'),
('Test Nama', 'Test Alamat'),
('New Nama', 'New Alamat'),
('Levi', 'Paradise'),
('Eren', 'Paradise'),
('Mikasa', 'Paradis'),
('Cak Gembul x yd f', 'Surabaya gg gg'),
('Mahdy', 'Cimahi');


CREATE TABLE IF NOT EXISTS `hobi` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `person_id` INT NOT NULL,
    `hobi` VARCHAR(200) NOT NULL,
    FOREIGN KEY (`person_id`) REFERENCES `person`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO `hobi` (`person_id`, `hobi`) VALUES
(1, 'Futsal'),
(1, 'Soccer'),
(1, 'Tenis Meja'),
(2, 'Basket'),
(2, 'Renang'),
(3, 'Futsal'),
(3, 'Membaca'),
(3, 'Renang'),
(3, 'Game'),
(4, 'Renang'),
(5, 'Jalan-Jalan');


